### ISSUE TITLE
stocator connector does not watch for new files in Object Storage when doing spark streaming using textFileStream API 

### ISSUE THREAD

**Issue by charles2588** [SparkTC/stocator#133]
Reproduction steps:-
 Create a notebook on IBM DSX with object storage configuration code and
below code to stream from container container1.

val ssc = new StreamingContext( sc, Seconds(30) )
val lines = ssc.textFileStream("swift2d://container1." + name + "/*")
val words = lines.flatMap(_.split(" "))
val wordCounts = words.map(x => (x, 1)).reduceByKey(_ + _)
wordCounts.print()
ssc.start()

According to API documentation
https://spark.apache.org/docs/latest/api/java/org/apache/spark/streaming/StreamingContext.html#textFileStream%28java.lang.String%29

textFileStream creates an input stream that monitors a Hadoop-compatible filesystem for new files and reads them as text files (using key as LongWritable, value as Text and input format as TextInputFormat). Files must be written to the monitored directory by "moving" them from another location within the same file system. File names starting with . are ignored.

**Problem swift stocator connector streams all files from container rather just one single file**

**Comment by gilv** [comment]
@charles2588 @djalova not sure i understand. Spark does list and then by itself identify "new" files that were added to the bucket. Spark doesn't perform list based on timestamp, since this functionality doesn't supported by object stores. 
If the request is to list files - then Stocator will list them as is

**Comment by gilv** [comment]
fixed by @djalova

**Comment by djalova** [comment]
I think this might still be an issue. Spark seems to check if a path given is a directory when using `textFileStream`. When the root path is given, Stocator doesn't return a `FileStatus` for it so it can't accept the root path as a directory.

**Comment by gilv** [comment]
@djalova can we close the issue?

**Comment by djalova** [comment]
@gilv I think it can be closed now
