### ISSUE TITLE
Special characters support in container and service name

### ISSUE THREAD

**Issue by apyasic** [SparkTC/stocator#139]
For example, given the following URI "swift2d://TimeRollingPolicy Test.Object Storage-7i/"  (percent-encoded version "swift2d://TimeRollingPolicy%20Test.Object%20Storage-7i/") 
Stocator should be able to create container "TimeRollingPolicy Test" (space between policy and test) using service "Object Storage-7i" (space between Object and Storage).

It is required to define clear policy regarding URI encoding method for stocator clients (for example, percent-encoding according to RFC 2396).

**Comment by apyasic** [comment]
Here are some findings that might be helpful:
1. [ObjectStoreFileSystem](https://github.com/SparkTC/stocator/blob/master/src/main/java/com/ibm/stocator/fs/ObjectStoreFileSystem.java).initialize method contains the following URI initialization logic:
uri = URI.create(fsuri.getScheme() + "://" + fsuri.getAuthority());
fs.getAuthority() method performs URI authority decoding which causes to exception when URI container or service name contains spaces even if URI authority is already encoded.
2. [SwiftAPIClient] (https://github.com/SparkTC/stocator/blob/master/src/main/java/com/ibm/stocator/fs/swift/SwiftAPIDirect.java) should receive decoded container and service name (strings with spaces) to work properly.

**Comment by gilv** [comment]
@apyasic is this for container or object names? Do you have issues also with object names?

**Comment by apyasic** [comment]
@gilv special characters in object names working properly. Issue title is updated accordingly.

**Comment by gilv** [comment]
@djalova Do you think we can support special characters in container name? As far as i remember in Hadoop it suppose to be container.<service> and the "." is the separation.

**Comment by djalova** [comment]
@gilv I'm currently looking into this. I think it should be possible.

**Comment by apyasic** [comment]
@djalova thank you! please note, that special characters support is also required for the service name, as bluemix default service name convention for swift is "Object Storage-<suffix>".

**Comment by gilv** [comment]
@apyasic Can you please checkout the PR from @djalova and that it is working as you expect?

**Comment by gilv** [comment]
@apyasic @djalova  We don't need to support special characters in service names. The service name in Bluemix and in Stocator are two different things. They are not related one to another.

I agree we can support special characters in container names, object names. Object names we already support
