### ISSUE TITLE
SwiftTestUtils.java lacks ASF copyright header

### ISSUE THREAD

**Issue by steveloughran** [SparkTC/stocator#144]
[SwiftTestUtils](https://github.com/SparkTC/stocator/blob/master/src/test/java/com/ibm/stocator/fs/swift2d/systemtests/SwiftTestUtils.java) is clearly based on Hadoop's [Contract Test Utils](https://github.com/apache/hadoop/blob/trunk/hadoop-common-project/hadoop-common/src/test/java/org/apache/hadoop/fs/contract/ContractTestUtils.java). This is particularly obvious to those of us who helped write those tests & the test utils.

Please reinstate the ASF copyright header on this and any related files.

If all you need is a stable version of the {{ContractTestUtils}} APIs, that's something which could be discussed on the hadoop common list. While written to validate FS behaviour, many of the assertions are useful enough we should think about releasing them in some public form.

**Comment by gilv** [comment]
@steveloughran thanks for pointing this.
