### ISSUE TITLE
Swift tenant configuration on a per job basis

### ISSUE THREAD

**Issue by samos123** [SparkTC/stocator#17]
For my use case I would like to have the ability to specify the Swift tenant credentials on a per tenant basis. Currently this is configured through xml files. Is there any way to dynamically specify the tenant credentials through spark context or similar?

**Comment by gilv** [comment]
@samos123 Of course. You don't need to use xml files.
Spark allows you to provide Hadoop configuration in run time, for example
sc.hadoopConfiguration.set("KEY","VALUE")

**Comment by samos123** [comment]
Handy to know. Thanks!
