### ISSUE TITLE
Create method should generate objects with correct content-type

### ISSUE THREAD

**Issue by gilv** [SparkTC/stocator#18]
create(...) method in ObjectStoreFileSystem uses wrong content-type for generated objects:

`FSDataOutputStream outStream = storageClient.createObject(objNameModified, "binary/octet-stream", metadata, statistics);
`

This should be somehow resolved to correct content-type. It would be good to know how other Hadoop drivers resolves content-types. We need to decide wether we should have correct content-type or leave "binary/octet-stream" as is

**Comment by jasoncl** [comment]
I found an example in Hadoop test where it uses "application/octet-stream" for its content-type.
[https://github.com/apache/hadoop/blob/2e1d0ff4e901b8313c8d71869735b94ed8bc40a0/hadoop-hdfs-project/hadoop-hdfs-httpfs/src/test/java/org/apache/hadoop/fs/http/server/TestHttpFSServer.java]

Looks like "binary/octet-stream" is not one of the predefined content type according to
[https://www.w3.org/Protocols/rfc1341/4_Content-Type.html]

The swift server doesn't really need to know the type of the files it is receiving, as it simply just writes to the object storage and does not really do any additional processing/displaying. Maybe the only thing we need to do is to change "binary/octet-stream" to "application/octet-stream"?

**Comment by gilv** [comment]
@jasoncl Do you know what content type should be when  someone store gzip file by using existing Hadoop drivers? Is it also application/octet-stream?

**Comment by jasoncl** [comment]
@gilv Looks like Hadoop http client in HttpFSFileSystem.java sets Content-Type to be UPLOAD_CONTENT_TYPE, which is "application/octet-stream". Hadoop http server in CheckUploadContentTypeFilter.java specifically checks the Content-Type needs to be "application/octet-stream". 
[https://github.com/apache/hadoop/search?utf8=✓&q=UPLOAD_CONTENT_TYPE](https://github.com/apache/hadoop/search?utf8=✓&q=UPLOAD_CONTENT_TYPE)
