### ISSUE TITLE
Problems with dynamically setting the configuration values.

### ISSUE THREAD

**Issue by anirupdutta** [SparkTC/stocator#22]
First of all thanks for this library. I was trying to test it out and encountered a few issues.

I tried with both Bluemix Keystone V3 and Legacy Softlayer Object Storage.
https://gist.github.com/anirupdutta/50434ef3ca87e850db3ded7ea877a744

Error trace
https://gist.github.com/anirupdutta/3de2e6f739889e019c1b2d80e272223e

Any idea what is causing this.

**Comment by anirupdutta** [comment]
- [ ] 

- [ ]

**Comment by anirupdutta** [comment]
butter fingered..

**Comment by anirupdutta** [comment]
https://github.com/SparkTC/stocator/blob/master/src/main/java/com/ibm/stocator/fs/swift/SwiftAPIClient.java#L175
Doesn't seem right....

**Comment by anirupdutta** [comment]
I was able to make it work with swauth by changing the tenant name to swift account name. But just that you know in case of swauth, this is considered to be the full user name:
SLOS****-2:anirup.dutta

If we just do this, it will work with JOSS

val config = new AccountConfig()
config.setAuthUrl("https://dal05.objectstorage.softlayer.net/auth/v1.0/")
config.setUsername("SLOS****-2:anirup.dutta")
config.setPassword(args(1))
config.setAuthenticationMethod(AuthenticationMethod.TEMPAUTH)
val account = new AccountFactory(config).createAccount()

**Comment by gilv** [comment]
@anirupdutta I am not sure i follow the problem. Did you followed steps on the Stocator documentation how to work with Bluemix object store service? It has detail section with example and explanation and key mappings and so on. Did you tried this?

**Comment by anirupdutta** [comment]
Okay so here is the swauth code: It works
https://gist.github.com/anirupdutta/f2f508dd73feb8dc1df26a547709ed81

Here is the keystone v2.0 code based on the [readme ](https://github.com/SparkTC/stocator/blob/master/README.md)

https://gist.github.com/anirupdutta/8b3338d60684865fd62d5fe733f0067f

It fails but I am quite sure it is happening due to JOSS as the keystone V2.0 tries authentication with the same credentials outside JOSS. I am sure the credentials are right because I used them from command line.

**Comment by gilv** [comment]
@anirupdutta  Bluemix object service is Keystone V3, not V2

**Comment by gilv** [comment]
@anirupdutta I commented on your gist. What exactly you want to achieve? To connect to public SoftLayer object store or Bluemix object service?
This is my configuration i use to access Bluemix object service
[https://gist.github.com/gilv/1bf64ba17bdc8190818bb85ba7220ec3](https://gist.github.com/gilv/1bf64ba17bdc8190818bb85ba7220ec3)

**Comment by anirupdutta** [comment]
First of all I cannot modify any core-site.xml files. I am using Bluemix Spark as a Service so I don't have access to the environment. I have to set the values dynamically. 

Bluemix object store is essentially Softlayer object storage which supports keystone auth. I am from the object storage dev team.

So I want to use keystone instead of using swauth for authenticating. 
Keystone V2 isn't turned off and yes it is not officially supported but it works in almost all practical cases. I am receiving the same authentication errors when trying to use V3. Everything works fine when I use the CLI.

Can you try instead of setting the values in core-site.xml, try to set them dynamically at run time and see if it works.

**Comment by gilv** [comment]
@anirupdutta ok, got it. Few clarifications: SoftLayer when accessed directly using Swiftauth. Bluemix object service uses Keystone v3. it's 2 different things. 

You don't need core-site.xml to access any of them. You can setup access details in the code and you already did it in your SoftLayer example Gist.

Copy the keys from the core-sites.xml that i showed you and setup those keys in your code. This way you will be able to access Bluemix object service.

There is no Keystone V2 here.

**Comment by anirupdutta** [comment]
Bluemix and Softlayer object store are same. 
Bluemix object store basically allows to authenticate using keystone V3 API and access object storage but they are same backend. I am from SL object storage dev team :)

Yes and it didn't work when I tried using with Keystone v3 or v2. 
I don't want to use swauth for authenticating.

https://github.com/SparkTC/stocator/commit/c650747fc27a200dcff7b5b361f019cd950111c8
I see this pull request. Any chance it may have introduced an issue?

**Comment by anirupdutta** [comment]
Issue is resolved. Thanks @gilv for the help.
