### ISSUE TITLE
Support compression

### ISSUE THREAD

**Issue by anirupdutta** [SparkTC/stocator#23]
Using the default swift connector, compression works out of the box. Compressing the data helps us to achieve significant performance gains, specially in our case where the files saved by one spark job will be processed by another job. We generate around 4-6 GB of data per hour. Compression helps us to reduce it to around 800 MB. 

If we can support something like this, it would be great.
    
val data = Array(1, 2, 3, 4, 5, 6, 7, 8)
    val distData = sc.parallelize(data)
    distData.saveAsTextFile("swift2d://logs.swauth/one1.txt", classOf[GzipCodec])

**Comment by gilv** [comment]
@anirupdutta Compression is certainly an important thing. It suppose to work with the old driver and the new driver, since compression doesn't happens inside the code, but in upper modules.
From your remark, i understand that you tried it with the old driver where it perfectly works and it's not working with the new driver? What exception you got? 
I will also try this with the new driver. It suppose to work and if not, may be some bug. I will make sure it works.

**Comment by gilv** [comment]
@anirupdutta I just checked and it works. I used Scala shell

import org.apache.hadoop.io.compress.GzipCodec
val data = Array(1, 2, 3, 4, 5, 6, 7, 8, 9)
val distData = sc.parallelize(data)
distData.saveAsTextFile("swift2d://gz1.lvm/data.txt", classOf[GzipCodec])

Objects were created as gzip files.

**Comment by anirupdutta** [comment]
This is what I see when I turn on compression.

one1.txt
one1.txt/_SUCCESS
one1.txt/part-00000.gz-attempt_201604041019_0000_m_000000_0
one1.txt/part-00001.gz-attempt_201604041019_0000_m_000001_1
one1.txt/part-00002.gz-attempt_201604041019_0000_m_000002_2
one1.txt/part-00003.gz-attempt_201604041019_0000_m_000003_3
one1.txt/part-00004.gz-attempt_201604041019_0000_m_000004_4
one1.txt/part-00005.gz-attempt_201604041019_0000_m_000005_5
one1.txt/part-00006.gz-attempt_201604041019_0000_m_000006_6
one1.txt/part-00007.gz-attempt_201604041019_0000_m_000007_7

If you do with the old driver, it will generate something like this.
one1.txt/part-00007.gz

**Comment by gilv** [comment]
@anirupdutta But it still generate compressed gzip files and Spark can read those compressed files without problems. The object is "one1.txt", this what should be accessed from Spark.
The parts has different names, you are right. But it's not an issue. By the way, parts has different names based on the  Spark cluster. If you run in cluster and standalone you will have different names for the parts. Stocator also use different naming convention for parts.
Part names are hidden...only "one1.txt" is what accessed.

**Comment by anirupdutta** [comment]
@gilv I may be confused but one1.txt is just a 0 byte object with type application/directory. Anyway I think I understand what you are saying. I will test it to make sure it works.

(cleversafe)anirup@anirup-ibm:~$ swift stat logs one1.txt
         Account: AUTH_6b4ff923-4cd5-4001-b28e-9fb2e4f439c4
       Container: logs
          Object: one1.txt
    Content Type: application/directory
  Content Length: 0
   Last Modified: Mon, 04 Apr 2016 15:19:17 GMT
            ETag: d41d8cd98f00b204e9800998ecf8427e
Meta Data-Origin: stocator
   Accept-Ranges: bytes
     X-Timestamp: 1459783156.91805
      X-Trans-Id: tx4ceea593e2cf4ccda6b9a-00570297fa

**Comment by gilv** [comment]
@anirupdutta yeap :) this is how it works... empty object one1.txt and then parts written as /one1.txt/part-XXX and we also have an empty object one1.txt/_SUCCESS

**Comment by gilv** [comment]
@anirupdutta  but all is hidden, unless you browse object store directly... from end user point of view only "one1.txt" is exists.

**Comment by anirupdutta** [comment]
@gilv Good to know. New to spark :)
