### ISSUE TITLE
Expand unitest and functional tests coverage.

### ISSUE THREAD

**Issue by gilv** [SparkTC/stocator#27]

**Comment by jasoncl** [comment]
@gilv, I can help with this. Which functional test area should I be focusing on first?

**Comment by gilv** [comment]
@jasoncl thanks.  i think the current unitest and functional tests are very weak. So any addition to this - would be very valuable. We need unitests that will cover much more functions that we have today.
See ObjectStoreFileSystemTest and SwiftAPIClientTest. They should be expanded to cover much more functionality. They both use powermock package. We should extend them both and also write more tests based on powermock to cover other classes.
