### ISSUE TITLE
The 403 Forbidden error is ignored at PUT flow

### ISSUE THREAD

**Issue by DmitrySot** [SparkTC/stocator#29]
the configuration:
I have 2 users defined at keystone:
user1
user2

I have two containers, they allowed a read access to both users, but write access allowed only to one user per container:
user1 can write to container1 (but not to container2)
user2 can write to container1 (but not to container1)

if I try to write to the wrong container with wrong credentials I got 403 forbidden error

but when I try to upload a new object through stocator - stocarot ignore 403 forbidden error - and it looks like the upload succeed, but of course I don't have that object written to the container.  

I think the problem is that stocator uses the 100-continue for chunked upload, but does not check the returned value

the problem can be reproduced by setting the system to defined configuration, and running the following code, when the user2 will be used for authentication  

from pyspark import SparkContext
from pyspark.sql import SQLContext
from pyspark.sql.types import *
import sys

sc = SparkContext()
sqlContext = SQLContext(sc)

myList = [[1,'a'],[2,'b'],[3,'c'],[4,'d'],[5,'e'],[6,'f']]
parallelList = sc.parallelize(myList).collect()
schema = StructType([StructField('column1', IntegerType(), False),
                     StructField('column2', StringType(), False)])
df = sqlContext.createDataFrame(parallelList, schema)
dfTarget = df.coalesce(1)
dfTarget.write.parquet("swift2d://container1.spark/myobject")
print "Done!"

**Comment by gilv** [comment]
Done.
