### ISSUE TITLE
AttributeError: 'SparkContext' object has no attribute 'hadoopConfiguration'

### ISSUE THREAD

**Issue by snowch** [SparkTC/stocator#30]
I'm not sure if this is a bug or user error.

See the details of the ticket at: https://github.com/snowch/biginsight-examples/issues/28

**Comment by snowch** [comment]
This was user error.  From python I need to use:

```
sc._jsc.hadoopConfiguration().set('my.mapreduce.setting', 'someVal')
```

**Comment by szeitlin** [comment]
thank you, this helped me!

**Comment by reergymerej** [comment]
https://stackoverflow.com/a/32661336/1319850
