### ISSUE TITLE
Question: Is is possible to read data from swift with this library?

### ISSUE THREAD

**Issue by snowch** [SparkTC/stocator#31]
The example on the README is just for writing data to swift.  Is reading supported?

**Comment by Nosfe** [comment]
@snowch Yes it is possible.

**Comment by snowch** [comment]
@Nosfe are you able to share any example code, preferably python?

**Comment by Nosfe** [comment]
@snowch 

Using a Jupyter notebook:

from pyspark import SparkConf, SparkContext

conf = (
    SparkConf()
    .set("spark.hadoop.fs.swift2d.impl", "com.ibm.stocator.fs.ObjectStoreFileSystem")
    .set("spark.hadoop.fs.swift2d.service.sahara.username","username")
    .set("spark.hadoop.fs.swift2d.service.sahara.password","password")
    .set("spark.hadoop.fs.swift2d.service.sahara.tenant","tenant")
    .set("spark.hadoop.fs.swift2d.service.sahara.auth.url","http://swift:5000/v2.0/tokens/")
    .set("spark.hadoop.fs.swift2d.service.sahara.auth.method","keystone")
       )
sc.stop()
sc=SparkContext(conf=conf)
words = sc.textFile("swift2d://gutenberg.sahara/gutenberg_big_2x.txt")
num_lines = words.count()
print("the number of lines in file", num_lines)

**Comment by snowch** [comment]
Thanks @Nosfe
