### ISSUE TITLE
Delete swift files/containers with stocator?

### ISSUE THREAD

**Issue by snowch** [SparkTC/stocator#32]
I have saved rdds to swift.  I now need to clean up some containers.

```python
    sc = SparkContext()

    prefix = "fs.swift2d.service." + service_name

    sc._jsc.hadoopConfiguration().set("fs.swift2d.impl","com.ibm.stocator.fs.ObjectStoreFileSystem")

    sc._jsc.hadoopConfiguration().set(prefix + ".auth.url",     "https://identity.open.softlayer.com/v3/auth/tokens")
    sc._jsc.hadoopConfiguration().set(prefix + ".public",       "true")
    sc._jsc.hadoopConfiguration().set(prefix + ".tenant",       project_id)
    sc._jsc.hadoopConfiguration().set(prefix + ".password",     password)
    sc._jsc.hadoopConfiguration().set(prefix + ".username",     username)
    sc._jsc.hadoopConfiguration().set(prefix + ".auth.method", "keystoneV3")
    sc._jsc.hadoopConfiguration().set(prefix + ".region",      "dallas")

    sqlContext = SQLContext(sc)

    # read file from HDFS
    lines = sc.textFile(license_filename, 1)
    counts = lines.flatMap(lambda x: x.split(' ')) \
                  .map(lambda x: (x, 1)) \
                  .reduceByKey(add) \
                  .filter(lambda x: x[0].isalnum())

    # Create a sql dataframe from the counts dataframe
    hhdf = sqlContext.createDataFrame(counts,['letter', 'count'])

    # destination url
    swift_file_url = "swift2d://{0}.{1}/counts".format(container, service_name)

    # save to swift
    counts.saveAsTextFile(swift_file_url)

    # some code omitted for brevity

    ### how can I delete the container at swift_file_url?
```

Is it possible to delete swift files/containers with stocator?  If so, please provide an example:

**Comment by gilv** [comment]
@snowch Spark doesn't provide you a way to delete objects. You have to delete them externally, like use REST client to access your object store directly or some UI console that object store exposes.
Stocator implements FileSystem interface, it contains DELETE method, but it means you need to call FileSystem API directly, bypassing Spark.

**Comment by snowch** [comment]
@gilv which object would I call the delete method on?  Would it be counts?
```
 counts.delete()
```

**Comment by gilv** [comment]
@snowch It's raw example, but you can get the idea...

import org.apache.hadoop.fs.FileSystem;
import org.apache.hadoop.fs.Path;

import java.io.IOException;
import java.net.URI;

	public class Test{		
		private static Configuration mConf = new Configuration(true);
		public static void main(String[] args) {
	        mConf.set("fs.swift2d.impl","com.ibm.stocator.fs.ObjectStoreFileSystem");
                <SET THE REST >
	        String publicURL = "swift2d://......";
	        FileSystem fs = null;
	        try {
	        	fs = FileSystem.get(URI.create(publicURL), mConf);
	        	fs.delete(YOUR PATH)
	        } catch ( IOException e) {
	        	System.out.println("ahh....I got an error");
	        	e.printStackTrace();
	        }
		}
	}

**Comment by snowch** [comment]
Perfect - thanks @gilv
