### ISSUE TITLE
create object doesn't work in SSL enabled mode

### ISSUE THREAD

**Issue by gilv** [SparkTC/stocator#33]
Create method uses wrong HTTP package that doesn't natively supports SSL mode.

We should use org.apache.commons.httpclient.methods.PutMethod instead of the current implementation. The package org.apache.commons.httpclient.methods.PutMethod internally supports SSL mode. This will make SSL mode work as expected when creating new objects.

Current code will throw 

bicluster#7|Traceback (most recent call last):
bicluster#7|  File "/home/biadmin/test-1461009081582/exporttoswift.py", line 73, in <module>
bicluster#7|    counts.saveAsTextFile(swift_file_url)
bicluster#7|  File "/usr/iop/4.1.0.0/spark/python/lib/pyspark.zip/pyspark/rdd.py", line 1508, in saveAsTextFile
bicluster#7|  File "/usr/iop/4.1.0.0/spark/python/lib/py4j-0.8.2.1-src.zip/py4j/java_gateway.py", line 538, in __call__
bicluster#7|  File "/usr/iop/4.1.0.0/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 36, in deco
bicluster#7|  File "/usr/iop/4.1.0.0/spark/python/lib/py4j-0.8.2.1-src.zip/py4j/protocol.py", line 300, in get_return_value
bicluster#7|py4j.protocol.Py4JJavaError: An error occurred while calling o86.saveAsTextFile.
bicluster#7|: java.lang.NullPointerException
bicluster#7|    at org.apache.hadoop.security.SecurityUtil.buildDTServiceName(SecurityUtil.java:257)
bicluster#7|    at org.apache.hadoop.fs.FileSystem.getCanonicalServiceName(FileSystem.java:302)
bicluster#7|    at org.apache.hadoop.fs.FileSystem.collectDelegationTokens(FileSystem.java:524)
bicluster#7|    at org.apache.hadoop.fs.FileSystem.addDelegationTokens(FileSystem.java:508)
bicluster#7|    at org.apache.hadoop.mapreduce.security.TokenCache.obtainTokensForNamenodesInternal(TokenCache.java:121)
bicluster#7|    at org.apache.hadoop.mapreduce.security.TokenCache.obtainTokensForNamenodesInternal(TokenCache.java:100)
bicluster#7|    at org.apache.hadoop.mapreduce.security.TokenCache.obtainTokensForNamenodes(TokenCache.java:80)
bicluster#7|    at org.apache.hadoop.mapred.FileOutputFormat.checkOutputSpecs(FileOutputFormat.java:126)
bicluster#7|    at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1.apply$mcV$sp(PairRDDFunctions.scala:1089)
bicluster#7|    at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1.apply(PairRDDFunctions.scala:1065)
bicluster#7|    at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1.apply(PairRDDFunctions.scala:1065)
bicluster#7|    at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
bicluster#7|    at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:108)
bicluster#7|    at org.apache.spark.rdd.RDD.withScope(RDD.scala:306)
bicluster#7|    at org.apache.spark.rdd.PairRDDFunctions.saveAsHadoopDataset(PairRDDFunctions.scala:1065)
bicluster#7|    at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$4.apply$mcV$sp(PairRDDFunctions.scala:989)
bicluster#7|    at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$4.apply(PairRDDFunctions.scala:965)
bicluster#7|    at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$4.apply(PairRDDFunctions.scala:965)
bicluster#7|    at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
bicluster#7|    at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:108)
bicluster#7|    at org.apache.spark.rdd.RDD.withScope(RDD.scala:306)
bicluster#7|    at org.apache.spark.rdd.PairRDDFunctions.saveAsHadoopFile(PairRDDFunctions.scala:965)
bicluster#7|    at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$1.apply$mcV$sp(PairRDDFunctions.scala:897)
bicluster#7|    at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$1.apply(PairRDDFunctions.scala:897)
bicluster#7|    at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$1.apply(PairRDDFunctions.scala:897)
bicluster#7|    at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
bicluster#7|    at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:108)
bicluster#7|    at org.apache.spark.rdd.RDD.withScope(RDD.scala:306)
bicluster#7|    at org.apache.spark.rdd.PairRDDFunctions.saveAsHadoopFile(PairRDDFunctions.scala:896)
bicluster#7|    at org.apache.spark.rdd.RDD$$anonfun$saveAsTextFile$1.apply$mcV$sp(RDD.scala:1426)
bicluster#7|    at org.apache.spark.rdd.RDD$$anonfun$saveAsTextFile$1.apply(RDD.scala:1405)
bicluster#7|    at org.apache.spark.rdd.RDD$$anonfun$saveAsTextFile$1.apply(RDD.scala:1405)
bicluster#7|    at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
bicluster#7|    at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:108)
bicluster#7|    at org.apache.spark.rdd.RDD.withScope(RDD.scala:306)
bicluster#7|    at org.apache.spark.rdd.RDD.saveAsTextFile(RDD.scala:1405)
bicluster#7|    at org.apache.spark.api.java.JavaRDDLike$class.saveAsTextFile(JavaRDDLike.scala:522)
bicluster#7|    at org.apache.spark.api.java.AbstractJavaRDDLike.saveAsTextFile(JavaRDDLike.scala:47)
bicluster#7|    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
bicluster#7|    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
bicluster#7|    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
bicluster#7|    at java.lang.reflect.Method.invoke(Method.java:497)
bicluster#7|    at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
bicluster#7|    at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:379)
bicluster#7|    at py4j.Gateway.invoke(Gateway.java:259)
bicluster#7|    at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
bicluster#7|    at py4j.commands.CallCommand.execute(CallCommand.java:79)
bicluster#7|    at py4j.GatewayConnection.run(GatewayConnection.java:207)
bicluster#7|    at java.lang.Thread.run(Thread.java:745)

**Comment by djalova** [comment]
Is it possible to use javax.ssl.HttpsURLConnection for this?

**Comment by snowch** [comment]
@gilv where is the problem?  connecting to swift using https?

**Comment by gilv** [comment]
@snowch The problem in this code

 @Override
  public FSDataOutputStream createObject(String objName, String contentType,
      Map<String, String> metadata, Statistics statistics) throws IOException {
    URL url = new URL(getAccessURL() + "/" + objName);
    LOG.debug("PUT {}. Content-Type : {}", url.toString(), contentType);
    try {
      HttpURLConnection httpCon = (HttpURLConnection) url.openConnection();
      httpCon.setDoOutput(true);
      httpCon.setRequestMethod("PUT");
      httpCon.addRequestProperty("X-Auth-Token", getAuthToken());
      httpCon.addRequestProperty("Content-Type", contentType);
      if (metadata != null && !metadata.isEmpty()) {
        for (Map.Entry<String, String> entry : metadata.entrySet()) {
          httpCon.addRequestProperty("X-Object-Meta-" + entry.getKey(), entry.getValue());
        }
      }
      return new FSDataOutputStream(new SwiftOutputStream(httpCon),
          statistics);
    } catch (IOException e) {
      LOG.error(e.getMessage());
      throw e;
    }
  }

**Comment by gilv** [comment]
@djalova I don't know..perhaps.

**Comment by djalova** [comment]
@gilv If we just have to use HTTPS to upload an object, I was able to do it by changing
`      HttpURLConnection httpCon = (HttpURLConnection) url.openConnection();
` 
`      HttpsURLConnection httpCon = (HttpURLConnection) url.openConnection();
`
Since HttpsURLConnection is a subclass of HttpURLConnection it doesn't break any existing code. Although I don't have access to a BI cluster so I'm not if this solves the problem.

**Comment by snowch** [comment]
I just replaced java.net.HttpURLConnection with javax.net.ssl.HttpsURLConnection - still the same problem.

I also put a debugger on the spark job and it looks as though there aren't any DelegationTokens.  Is this a problem due to kerberos running on standard clusters, but not on basic clusters?

```
bicluster#7|: java.lang.NullPointerException
bicluster#7| at org.apache.hadoop.security.SecurityUtil.buildDTServiceName(SecurityUtil.java:257)
bicluster#7| at org.apache.hadoop.fs.FileSystem.getCanonicalServiceName(FileSystem.java:302)
bicluster#7| at org.apache.hadoop.fs.FileSystem.collectDelegationTokens(FileSystem.java:524)
bicluster#7| at org.apache.hadoop.fs.FileSystem.addDelegationTokens(FileSystem.java:508)
bicluster#7| at org.apache.hadoop.mapreduce.security.TokenCache.obtainTokensForNamenodesInternal(TokenCache.java:121)
bicluster#7| at org.apache.hadoop.mapreduce.security.TokenCache.obtainTokensForNamenodesInternal(TokenCache.java:100)
bicluster#7| at org.apache.hadoop.mapreduce.security.TokenCache.obtainTokensForNamenodes(TokenCache.java:80)```

**Comment by djalova** [comment]
I tried to trace through the code and it seems that SecurityUtil.buildDTServiceName gets called in FileSystem.getCanonicalServiceName using `SecurityUtil.buildDTServiceName(getUri(), getDefaultPort())`.
However when in Stocator's ObjectStoreFileSystem getURI() is implemented so that it always returns null.
Therefore when we get to the following piece of code in SecurityUtil.buildDTServiceName:
```
  public static String buildDTServiceName(URI uri, int defPort) {
    String authority = uri.getAuthority();    // NullPointerException
    if (authority == null) {
      return null;
    }
    InetSocketAddress addr = NetUtils.createSocketAddr(authority, defPort);
    return buildTokenService(addr).toString();
   }
```

**Comment by snowch** [comment]
It works ok on the basic cluster, but on a standard cluster it fails with a new exception:

```
06:44:01.419 [ERROR] [system.err] bicluster#8|16/04/21 05:44:00 INFO core.AbstractAccount: JOSS / Setting hash password
06:44:02.462 [QUIET] [system.out] bicluster#8|Traceback (most recent call last):
06:44:02.462 [QUIET] [system.out] bicluster#8|  File "/home/biadmin/test-1461217400521/exporttoswift.py", line 71, in <module>
06:44:02.463 [QUIET] [system.out] bicluster#8|    counts.saveAsTextFile(swift_file_url)
06:44:02.463 [QUIET] [system.out] bicluster#8|  File "/usr/iop/4.1.0.0/spark/python/lib/pyspark.zip/pyspark/rdd.py", line 1508, in saveAsTextFile
06:44:02.463 [QUIET] [system.out] bicluster#8|  File "/usr/iop/4.1.0.0/spark/python/lib/py4j-0.8.2.1-src.zip/py4j/java_gateway.py", line 538, in __call__
06:44:02.464 [QUIET] [system.out] bicluster#8|  File "/usr/iop/4.1.0.0/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 42, in deco
06:44:02.464 [QUIET] [system.out] bicluster#8|pyspark.sql.utils.IllegalArgumentException: java.net.UnknownHostException: 1461217400521.dallas
06:44:02.464 [ERROR] [system.err] bicluster#8|16/04/21 05:44:01 INFO spark.SparkContext: Invoking stop() from shutdown hook
```

**Comment by gilv** [comment]
@snowch @djalova Seems to be resolved in the last commit. 
@snowch can you please test it with the recent master code?

**Comment by snowch** [comment]
This fixes the issue for me.

**Comment by gilv** [comment]
Resolved

**Comment by snowch** [comment]
Thanks for fixing this.  When will a 1.0.2 release be expected?

**Comment by gilv** [comment]
@snowch i will try to handle it today

**Comment by snowch** [comment]
Awesome.  Thanks @gilv
