### ISSUE TITLE
Testing Stocator with Spark Streaming

### ISSUE THREAD

**Issue by gilv** [SparkTC/stocator#40]
We need to test that Stocator works with Spark Streaming.
This https://docs.cloud.databricks.com/docs/latest/databricks_guide/08%20Spark%20Streaming/08%20Write%20Output%20To%20S3.html contains very good example. 
We need to verify that it works with Stocator as well. 
It will be also good to document here if there are any modification to the example above in order to make it with work with Stocator.

**Comment by gilv** [comment]
@djalova Any chance you can look at it? Thanks

**Comment by djalova** [comment]
@gilv Sure, I'll look into this.

**Comment by djalova** [comment]
@gilv I tested this using the example in the link and found that Stocator works without having to modify any code.

**Comment by gilv** [comment]
@djalova Thanks a lot.
