### ISSUE TITLE
Improving cleanup process in the unitests

### ISSUE THREAD

**Issue by gilv** [SparkTC/stocator#52]
Many unitests create temp data. 
The way it works today is that each @Test creates it's data and then
`@After
  public void tearDown()`
responsible to clean the generated data.

This is highly inefficient since it happens for each test and not per test suite. We need to change the logic, so that temp data will be created only once in the setup() method and cleaned at the end of the class run:
`@AfterClass
  public static void classTearDown() throws Exception {
  }`
A good reference is TestSwiftFileSystemLsOperations. It suppose to create temp data only once and then clean it after all tests complete it's executions. The way it works today is that data is created and cleaned per function.

**Comment by gilv** [comment]
@djalova Can you please look at it?

**Comment by djalova** [comment]
Will submit a PR soon.

**Comment by gilv** [comment]
resolved
