### ISSUE TITLE
improved error handing

### ISSUE THREAD

**Issue by snowch** [SparkTC/stocator#54]
When an error is thrown by stocator, it is very difficult to find the cause of the error.  For example:

```
Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.collectAndServe.
: java.lang.NullPointerException
	at org.javaswift.joss.client.impl.ClientImpl.createAccount(ClientImpl.java:100)
	at org.javaswift.joss.client.impl.ClientImpl.createAccount(ClientImpl.java:27)
        ...
```

Stocator is quite difficult to work with because the error messages generally don't help you identify the root cause of the problem.

**Comment by gilv** [comment]
@snowch in general, Stocator provides many info when exception happens.
Can you show the whole trace? The exception you copy-paste here is from JOSS on create account.. this might happen when some auth related information is missing.
I need to see the whole flow, perhaps some scenarios in Stocator need better exception handling and provide better information.
