### ISSUE TITLE
i'm sorry i can't find the keystone v3 patch in the source code,can you give me one?and how to use it in joss?

### ISSUE THREAD

**Issue by RayOsLei** [SparkTC/stocator#62]

**Comment by gilv** [comment]
@RayOsLei Is it related Joss or Stocator? If joss - you should post those questions on the Joss forums.  This is what i am using in Stocator
https://github.com/SparkTC/stocator/blob/master/src/main/java/com/ibm/stocator/fs/swift/auth/PasswordScopeAccess.java

**Comment by RayOsLei** [comment]
It is related Joss,but joss forums don't tell me how to solve it ?

**Comment by gilv** [comment]
@RayOsLei sorry, i don't have any patch for Joss. Seems you misunderstand it.
