### ISSUE TITLE
Use HttpClient in SwiftOutputStream

### ISSUE THREAD

**Issue by gilv** [SparkTC/stocator#67]
We have to use HttpClient ( version 4 and up ) for the streaming upload.
Currently SwiftOutputStream uses HttpURLConnection to obtain ouputstream that is used for streaming. We should implement the same based on CloseableHttpClient, similar to what we do in SwiftAPIDirect.

**Comment by gilv** [comment]
@djalova Can you check this please?

**Comment by gilv** [comment]
@djalova  This seems to be relevant [(http://stackoverflow.com/questions/10146692/how-do-i-write-to-an-outputstream-using-defaulthttpclient)]

**Comment by djalova** [comment]
Sure, I'll take a look at it.

**Comment by gilv** [comment]
@djalova Thanks.

**Comment by gilv** [comment]
https://github.com/SparkTC/stocator/pull/72 based on #71.
