### ISSUE TITLE
Issues with Hadoop dependency on HttpClient

### ISSUE THREAD

**Issue by gilv** [SparkTC/stocator#74]
Stocator depends on   httpcomponents.httpcore.version 4.4.5 and httpcomponents.httpclient.version 4.5.2. However current Hadoop releases still depends on older versions
[INFO] +- org.apache.hadoop:hadoop-common:jar:2.7.2:provided
[INFO] |  +- net.java.dev.jets3t:jets3t:jar:0.9.0:provided
[INFO] |  |  - (org.apache.httpcomponents:httpclient:jar:4.1.2:provided - omitted for conflict with 4.2.1)
[INFO] |  - org.apache.hadoop:hadoop-auth:jar:2.7.2:provided
[INFO] |     - (org.apache.httpcomponents:httpclient:jar:4.2.5:provided - omitted for conflict with 4.1.2)

The issues with HttpClient versions are not affecting Stocator only and they were addressed in [https://issues.apache.org/jira/browse/HADOOP-12767].  Unfortunately [https://issues.apache.org/jira/browse/HADOOP-12767] was not merged into 2.7.3 or 2.7.2 but only in Hadoop 2.8

**Comment by gilv** [comment]
@djalova Can you estimate how complicated is to create another branch of Stocator that depends on httpclient:jar:4.1.2 ? In a short term this will allow us to run natively in Hadoop 2.7.x

**Comment by gilv** [comment]
Alternative solution is to apply those patches on the Hadoop 2.7.2-src, build it and then replace hadoop-commons.jar in the 2.7.2 distribution. You need to make sure to delete old httplient and httpcore from share/common/lib

**Comment by djalova** [comment]
@gilv I tried to create another branch that depended on httpclient 4.1.2 and ran into runtime errors because JOSS uses PoolingClientConnectionManager which was made available in 4.2.

**Comment by djalova** [comment]
Here's a link to my progress
https://github.com/djalova/stocator/tree/httpclient-4.1.2

**Comment by gilv** [comment]
We should also document that https://issues.apache.org/jira/browse/HADOOP-12767 ignored hadoop-openstack fixes

**Comment by gilv** [comment]
@djalova no need to work on 4.1.2 anymore. I will document the Hadoop issue on the wiki.
