### ISSUE TITLE
Stocator support for temp url

### ISSUE THREAD

**Issue by gilv** [SparkTC/stocator#97]
Stocator need to support temp url.

For example, consider the following temp url
https://mil01.objectstorage.softlayer.net/v1/AUTH_8f731319-18c3-4ce8-909f-df78b885df0a/testurl1/data.csv?temp_url_sig=ID&temp_url_expires=1479816450

To access it from Spark:

val d = sc.textFile("swift2d://testurl1.mil01/v1/AUTH_8f731319-18c3-4ce8-909f-df78b885df0a/testurl1/data.csv?temp_url_sig=ID&temp_url_expires=1479816450")

However Stocator will fail during listStatus(..)

**Comment by gilv** [comment]
@djalova Can you handle it please?

**Comment by gilv** [comment]
@michaelfactor FYI

**Comment by djalova** [comment]
Hi Gil,
 
Sure I can work on this. I just want to make sure that this temporary URL lasts for the rest of the week. I checked the expiration date and assuming that the number 1479816450 maps to a Unix timestamp, the URL seems to expire some time today.
 
Thanks,
Daniel Jalova
 
----- Original message -----From: Gil Vernik <notifications@github.com>To: SparkTC/stocator <stocator@noreply.github.com>Cc: Daniel Jalova/San Francisco/IBM@IBMUS, Mention <mention@noreply.github.com>Subject: Re: [SparkTC/stocator] Stocator support for temp url (#97)Date: Tue, Nov 22, 2016 4:14 AM 
@michaelfactor FYI
